apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ibookee-platform.fullname" . }}-{{ .Values.blueGreen.activeColor }}
  labels:
    app: {{ include "ibookee-platform.name" . }}
    color: {{ .Values.blueGreen.activeColor }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ibookee-platform.name" . }}
      color: {{ .Values.blueGreen.activeColor }}
  template:
    metadata:
      labels:
        app: {{ include "ibookee-platform.name" . }}
        color: {{ .Values.blueGreen.activeColor }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources: {{- toYaml .Values.resources | nindent 12 }} 