apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibookee-platform.fullname" . }}-{{ .Values.blueGreen.activeColor }}
  labels:
    app: {{ include "ibookee-platform.name" . }}
    color: {{ .Values.blueGreen.activeColor }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ibookee-platform.name" . }}
    color: {{ .Values.blueGreen.activeColor }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000 